### PR TITLE
Add the Gtk3 compatibility

### PR DESCRIPTION
**Pull request by XRevan86**
I did the work one month ago, now making the merge request finally.

### CODE REVIEW

**Comment by raveit65** [comment]
Really nice, resizing is working with this PR.

**Comment by raveit65** [comment]
I guess  'Use the correct signature for the "child-exited" signal handler of Vte Terminal' should be merged from other PR to have correct author infos in commit header ;-)

**Review by yselkowitz — CHANGES_REQUESTED** [review]
Overall, this looks fine.  At this point, we can drop backwards compatibility and require gtk3 and vte-2.91 unconditionally.  Would you be willing to rework this patch?

**Comment by XRevan86** [comment]
@yselkowitz, well, the "rework" is simply a removal of a few lines.
But if there are no plans on making big changes (thus making Gtk2 support a hassle), why is it a problem :-)?
> and vte-2.91

Eeh, vte 2.90 is still around…

**Comment by raveit65** [comment]
Any news?
or should i drop caja-terminal and python-caja in fedora if you don't have the time to maintain it?

**Pull request merged**
